name: leo-admission
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - -r requirements.txt
# Notes:
# - For PDF build, install TeXLive (xelatex) and pandoc via system package manager.
#   macOS: brew install --cask mactex; brew install pandoc
# - For Hypatia submodule, run: make hypatia-init
