/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AblationStudy: typeof import('./src/components/AblationStudy.vue')['default']
    AdmissionStats: typeof import('./src/components/AdmissionStats.vue')['default']
    BatchExperiments: typeof import('./src/components/BatchExperiments.vue')['default']
    DRLEnvironmentState: typeof import('./src/components/DRLEnvironmentState.vue')['default']
    DRLTrainingChart: typeof import('./src/components/DRLTrainingChart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    EventLog: typeof import('./src/components/EventLog.vue')['default']
    ExperimentMonitoring: typeof import('./src/components/ExperimentMonitoring.vue')['default']
    LogViewer: typeof import('./src/components/LogViewer.vue')['default']
    MetricCard: typeof import('./src/components/MetricCard.vue')['default']
    PerformanceChart: typeof import('./src/components/PerformanceChart.vue')['default']
    PositioningStats: typeof import('./src/components/PositioningStats.vue')['default']
    RealTimeChart: typeof import('./src/components/RealTimeChart.vue')['default']
    ResultsAnalysis: typeof import('./src/components/ResultsAnalysis.vue')['default']
    RewardBreakdown: typeof import('./src/components/RewardBreakdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticalReports: typeof import('./src/components/StatisticalReports.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
